M48
; DRILL file {KiCad (6.0.1)} date Fri May 20 13:38:32 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-20T13:38:32+06:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X7.8018Y-0.7972
X7.9986Y-0.7972
T2
X6.201Y-1.3509
X6.201Y-1.4691
T0
M30
